---
default_language_version:
  python: python3.10

repos:
  - hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
  - hooks:
      - args:
          - --py39-plus
        id: pyupgrade
    repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
  - hooks:
      - args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports
        id: autoflake
    repo: https://github.com/myint/autoflake
    rev: v1.4
  - hooks:
      - args: [--safe]
        id: black
    repo: https://github.com/psf/black
    rev: 22.1.0
  - hooks:
      - id: isort
    repo: https://github.com/PyCQA/isort
    rev: 5.10.1
  - hooks:
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
    repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
  - hooks:
      - id: prettier
        stages:
          - commit
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
  - hooks:
      - additional_dependencies:
          - flake8-blind-except
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-docstrings
          - flake8-polyfill
          - flake8-pytest
          - flake8-quotes
          - flake8-typing-imports
          - yesqa
        id: flake8
    repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
  - hooks:
      - additional_dependencies:
          - types-PyYAML
          - types-orjson
        args: [--show-error-codes, --python-version, "3.10"]
        id: mypy
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
  - hooks:
      - args: [-s, B101]
        exclude: tests/
        id: bandit
    repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
  - hooks:
      - args: [-i, E006]
        id: bashate
    repo: https://github.com/openstack/bashate
    rev: 2.1.0
  - hooks:
      - always_run: true
        entry: pytest -vv --durations 3
        id: pytest
        language: system
        name: pytest
        pass_filenames: false
        stages:
          - push
        types:
          - python
    repo: local
