# credits to https://github.com/andreoliwa
default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --remove-unused-variables,
            --remove-duplicate-keys,
            --ignore-init-module-imports,
          ]
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.1.0]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: rst-backticks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        stages: [commit]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          [
            flake8-blind-except,
            flake8-bugbear,
            flake8-comprehensions,
            flake8-debugger,
            flake8-docstrings,
            flake8-isort,
            flake8-polyfill,
            flake8-pytest,
            flake8-quotes,
            flake8-typing-imports,
            yesqa,
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args: [--show-error-codes, --python-version, "3.10"]
        additional_dependencies: [types-PyYAML]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [-s, B101]
        exclude: tests/
  - repo: https://github.com/openstack/bashate
    rev: 2.1.0
    hooks:
      - id: bashate
        args: [-i, E006]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.21.2
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [push]
        entry: pytest -vv --durations 3
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
